CREATE DATABASE bank_system;
GO
USE bank_system;

CREATE TABLE bank
(
	id INT IDENTITY PRIMARY KEY,
	name  NVARCHAR(30) NOT NULL
);

CREATE TABLE city
(
	id INT IDENTITY PRIMARY KEY,
	name  NVARCHAR(30) NOT NULL
);

CREATE TABLE branch
(
	id INT IDENTITY PRIMARY KEY,
	bank_id INT  NOT NULL REFERENCES bank(id) ON DELETE CASCADE,
	city_id INT  NOT NULL REFERENCES city(id) ON DELETE CASCADE,
);

CREATE TABLE social_status
(
	id INT IDENTITY PRIMARY KEY,
	name  NVARCHAR(30) NOT NULL
);

CREATE TABLE client
(
	id INT IDENTITY PRIMARY KEY,
	name  NVARCHAR(30) NOT NULL,
	soc_status_id INT  NOT NULL REFERENCES social_status(id) ON DELETE CASCADE,
);

CREATE TABLE account
(
	id INT IDENTITY PRIMARY KEY,
	balance INT NOT NULL,
	client_id INT  NOT NULL REFERENCES client(id) ON DELETE CASCADE,
	bank_id INT NOT NULL REFERENCES bank(id) ON DELETE CASCADE
);

CREATE TABLE card
(
	id INT IDENTITY PRIMARY KEY,
	balance INT NOT NULL,
	account_id INT  NOT NULL REFERENCES account(id) ON DELETE CASCADE,
);


